/**
 * Generated by orval v6.12.0 🍺
 * Do not edit manually.
 * Terence Api
 * Terence Api
 * OpenAPI spec version: 0.0.1
 */
import axios from 'axios'
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  Hello
} from './model'




  export const helloWorld = <TData = AxiosResponse<Hello>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/hello`,options
    );
  }

export type HelloWorldResult = AxiosResponse<Hello>
